### ISSUE TITLE
[FYI] Compatibility issue with EasyMail

### ISSUE THREAD

**Issue by tflo** [exochron/Favorite-Contacts#16]
I noticed that FC's "Directly open Write Mail on empty inbox" feature is not working if used together with [EasyMail](https://www.curseforge.com/wow/addons/easymail).

After inspection, it turned out that this is actually caused on EasyMail's side: They kill the _MailFrame's OnShow_ script at login time with a `SetScript`. So your hook is removed.

I have already opened an [issue over at EasyMail](https://legacy.curseforge.com/wow/addons/easymail/issues/26), suggesting to fix this (by using `HookScript` instead of `SetScript`). You also find more details there.

_So, currently, this post is just a **FYI**._

However, it seems that EasyMail hasn't seen updates for quite a while (besides the toc bumps), so I wouldn't be surprised if they don't fix it. It is also possible that they are using `SetScript` for some reason that escapes me.

In that case, this will be a great candidate for "stuffing" your ThirdPartySupport.lua file a bit 😉 (e.g. with a delayed second hook if EasyMail is loaded).

Thanks for FC,

– Tom

**Comment by exochron** [comment]
Although I'm not a big fan of fixing other peoples bugs (using SetScript() is just pure evil at work.), I was able to come up with a little workaround.
The hooks are now set on demand. So that gives EasyMail enough time Set everything up. :)

fixed with version 2.11

**Comment by tflo** [comment]
> Although I'm not a big fan of fixing other peoples bugs 

100% agree, but currently there aren’t many good and working mail addons besides FC (actually I think EasyMail is the only one worth using, albeit not as “mandatory” as FC), so implementing workarounds for the flaws of the (few) others is a good and friendly thing towards the users who can’t fix it themselves.

I mean, if we face an interfering  Blizz bug or flaw, we also try to work around that, instead of waiting months/years for them to fix it, right? 😉

(Also, I felt compelled to let you know about this by the mere presence of your ThirdPartySupport.lua file.)

Thanks for your work!
