### ISSUE TITLE
2.10.1 drops mainline for classic

### ISSUE THREAD

**Issue by torkus** [exochron/Favorite-Contacts#21]
It might be intentional or it might be a typo, but is `11000` supposed to be `110000` ?

https://github.com/exochron/Favorite-Contacts/commit/ec969a4b896b020fdd74d7cda7bf6543c89060ac#diff-62a01dcc88834dea46cc93a0bcb30fb2cf1560f20afb2388a240e47019bcce77R1

**Comment by torkus** [comment]
And possibly the same with `MouseoverPortrai`:

https://github.com/exochron/MouseoverPortrai/compare/3.1.2...3.1.3#diff-81500072d62605369d7d4c862552b6e00da080f2a2c4cf6f6e342163440e01abR1

**Comment by exochron** [comment]
f*ck, yeah thats a typo :see_no_evil: 
thank you for noticing

**Comment by exochron** [comment]
all addons are updated. again, thank you for spotting this :)
