### ISSUE TITLE
GetAddOnMetadata replaced in 11.0.2

### ISSUE THREAD

**Issue by lakhpache** [exochron/Favorite-Contacts#22]
GetAddonMetadata function has been removed & replaced with C_AddOns.GetAddonMetadata

The two functions are basically identical - you can do a search & replace of the three instances of the function in SettingsPanel.lua and Favorite Contacts will work again with no problems.

But without the change it's not possible to alter settings & the addon throws up the following bugsack error:

`32x FavoriteContacts/SettingsPanel.lua:141: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@FavoriteContacts/SettingsPanel.lua"]:141: in function <FavoriteContacts/SettingsPanel.lua:140>
[string "@FavoriteContacts/SettingsPanel.lua"]:223: in function <FavoriteContacts/SettingsPanel.lua:222>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@FavoriteContacts/FavoriteContacts.lua"]:114: in function <FavoriteContacts/FavoriteContacts.lua:112>

Locals:
(*temporary) = nil
(*temporary) = "FavoriteContacts"
(*temporary) = "Title"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)"
ADDON_NAME = "FavoriteContacts"
AceGUI = <table> {
 objPools = <table> {
 }
 WidgetBase = <table> {
 }
 counts = <table> {
 }
 LayoutRegistry = <table> {
 }
 tooltip = AceGUITooltip {
 }
 WidgetRegistry = <table> {
 }
 WidgetVersions = <table> {
 }
 WidgetContainerBase = <table> {
 }
}
ADDON = <table> {
 CONTACT_BUTTON_SIZE = 36
 L = <table> {
 }
 settings = <table> {
 }
 CONTACT_BUTTON_MARGIN = 3
 Events = <table> {
 }
 iconFiles = <table> {
 }
}`

**Comment by exochron** [comment]
fixed with version 2.10.3
